name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: "abinbabu2001"  
          password: "abinBabu@2001"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Root context to cover all services
          push: true
          tags: abinbabu2001/blog-microservices:latest

      - name: Log out from Docker Hub
        run: docker logout
